//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMenu.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approvisionnement
    {
        public int idApp { get; set; }
        public string CodeProduit { get; set; }
        public Nullable<double> QteAppro { get; set; }
        public Nullable<double> QteRestant { get; set; }
        public Nullable<System.DateTime> DatePeremption { get; set; }
        public string DateAppro { get; set; }
    }
}
