//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMenu.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        public int idProfil { get; set; }
        public string CodeProfil { get; set; }
        public string LibelleProfil { get; set; }
    }
}
