//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMenu.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VListeProduitCategorie
    {
        public string CodeCategorie { get; set; }
        public string libelleCategori { get; set; }
        public string CodeProduit { get; set; }
        public string DesignationProduit { get; set; }
        public Nullable<double> PU { get; set; }
        public Nullable<int> QteMin { get; set; }
        public Nullable<int> QteCri { get; set; }
        public int IdProduit { get; set; }
    }
}
